name = "uno-game"
main = "src/index.js"
compatibility_date = "2026-03-28"

[[durable_objects.bindings]]
name = "UNO_ROOM"
class_name = "UnoRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UnoRoom"]
